plugins {
    id 'java'
    id 'org.web3j' version '4.13.0'
}

group = 'org.omnione.did'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
    google()
    maven { url 'https://maven.google.com/' }
    maven { url 'https://mvnrepository.com/artifact/' }
}

ext {
    set('web3jCoreVersion', '4.13.0')
    set('fabricGatewayVersion', '2.2.9')
}

dependencies {
    implementation files("libs/did-datamodel-sdk-server-1.0.0.jar")
    implementation("org.hyperledger.fabric:fabric-gateway-java:${fabricGatewayVersion}")
    implementation("org.web3j:core:${web3jCoreVersion}")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.15.2")
    implementation("org.apache.commons:commons-pool2:2.12.0")
    annotationProcessor("com.fasterxml.jackson.core:jackson-databind:2.15.2")
    annotationProcessor("org.projectlombok:lombok:1.18.28")
    compileOnly("org.projectlombok:lombok:1.18.28")
}

test {
    useJUnitPlatform()
}